name: 'Get iTunes Headers & Kbsync'
inputs:
  apple_id:
    required: true
  apple_id_pwd:
    required: true
  ngrok_token:
    description: "Token for RDP debugging"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check if initialized
      id: check
      run: |
        echo "Checking if we need to initialize iTunes again"
        if [[ "$(cat /c/.iTunesInitialized)" == "${{ inputs.ngrok-token }}" ]]; then
          echo "  Need to re-init iTunes"
          echo "::set-output name=NEED_INIT::1"
        else
          echo "  Needn't to do anything"
          echo "::set-output name=NEED_INIT::0"
        fi
      shell: bash
    - name: Setup iTunes
      if: ${{ steps.check.outputs.NEED_INIT == 1 }}
      run: |
        echo Setup iTunes...
        start /wait taskkill /f /im iTunes* python*
        workflow_helper\iTunesInstall\install_itunes.bat
      shell: cmd
    
    - name: Setup Python Dependencies
      if: ${{ steps.check.outputs.NEED_INIT == 1 }}
      run: |
        echo Setup Python Dependencies...
        pip3 install pywinauto frida Flask
      shell: cmd

    - uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      if: ${{ always() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
        ngrok-token: ${{ inputs.ngrok_token }}
        password: Aa123456
        foreground: true

    - name: Login iTunes
      if: ${{ steps.check.outputs.NEED_INIT == 1 }}
      env:
        APPLEID: ${{ inputs.apple_id }}
        APPLEID_PWD: ${{ inputs.apple_id_pwd }}
      run: |
          echo Login iTunes...
          python3 workflow_helper/itunes_auto_login.py %APPLEID% %APPLEID_PWD%
      shell: cmd
    
    - name: Finish Initialization
      if: ${{ steps.check.outputs.NEED_INIT == 1 }}
      env:
        APPLEID: ${{ inputs.apple_id }}
      run: |
        echo "Finish Initialization..."
        echo "$APPLEID" > /c/.iTunesInitialized
      shell: bash
    
    - name: Start Frida Header Server
      run: |
          echo Start Frida Header Server!
          start python3 workflow_helper\iTunesDownload\get_header.py
      shell: cmd
